# Generated by Django 4.2.15 on 2024-08-08 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_client_joined_on_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='cms.client'),
        ),
    ]
