# Generated by Django 4.2.15 on 2024-08-08 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_note_client'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carer',
            options={'ordering': ['-user']},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['-last_name', 'first_name']},
        ),
    ]
