# Generated by Django 4.2.15 on 2024-08-09 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_alter_carer_options_alter_client_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carer',
            options={'ordering': ['-user__username']},
        ),
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterField(
            model_name='note',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='cms.client'),
        ),
    ]
