# Generated by Django 4.2.15 on 2024-08-11 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_alter_carer_options_alter_note_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='condition',
            field=models.TextField(default='Please describe the clients condition'),
        ),
    ]
