# Generated by Django 4.2.15 on 2024-08-11 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_note_condition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='condition',
        ),
        migrations.AddField(
            model_name='client',
            name='condition',
            field=models.TextField(default='Please describe the clients condition'),
        ),
    ]
