# Generated by Django 4.2.15 on 2024-08-12 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_remove_note_condition_client_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
