# Generated by Django 4.2.15 on 2024-08-13 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_alter_note_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='condition',
            field=models.TextField(default='Describe the clients condition'),
        ),
    ]
